<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="205630" started-at="2022-04-12T12:35:35Z" finished-at="2022-04-12T12:39:01Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="205630" started-at="2022-04-12T12:35:35Z" finished-at="2022-04-12T12:39:01Z">
      <class name="SeleniumFrameworkWithTestNg.CreateProductTest">
        <test-method status="PASS" signature="OpenDataBase()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="OpenDataBase" is-config="true" duration-ms="39" started-at="2022-04-12T12:35:35Z" finished-at="2022-04-12T12:35:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenDataBase -->
        <test-method status="PASS" signature="ParallelExecution()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="ParallelExecution" is-config="true" duration-ms="0" started-at="2022-04-12T12:35:35Z" finished-at="2022-04-12T12:35:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ParallelExecution -->
        <test-method status="PASS" signature="LaunchBrowser()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="LaunchBrowser" is-config="true" duration-ms="58181" started-at="2022-04-12T12:35:35Z" finished-at="2022-04-12T12:36:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method status="PASS" signature="LoginToApplication()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="LoginToApplication" is-config="true" duration-ms="25734" started-at="2022-04-12T12:36:33Z" finished-at="2022-04-12T12:36:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="SKIP" signature="CreatePro()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="CreatePro" duration-ms="35866" started-at="2022-04-12T12:36:59Z" finished-at="2022-04-12T12:37:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at SeleniumFrameworkWithTestNg.CreateProductTest.CreatePro(CreateProductTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatePro -->
        <test-method status="PASS" signature="LogoutFromApplication()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="LogoutFromApplication" is-config="true" duration-ms="5098" started-at="2022-04-12T12:37:35Z" finished-at="2022-04-12T12:37:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutFromApplication -->
        <test-method status="PASS" signature="LoginToApplication()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="LoginToApplication" is-config="true" duration-ms="5290" started-at="2022-04-12T12:37:40Z" finished-at="2022-04-12T12:37:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="SKIP" signature="CreatePro()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="CreatePro" duration-ms="22262" started-at="2022-04-12T12:37:46Z" finished-at="2022-04-12T12:38:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at SeleniumFrameworkWithTestNg.CreateProductTest.CreatePro(CreateProductTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatePro -->
        <test-method status="PASS" signature="LogoutFromApplication()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="LogoutFromApplication" is-config="true" duration-ms="2660" started-at="2022-04-12T12:38:08Z" finished-at="2022-04-12T12:38:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutFromApplication -->
        <test-method status="PASS" signature="LoginToApplication()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="LoginToApplication" is-config="true" duration-ms="4771" started-at="2022-04-12T12:38:11Z" finished-at="2022-04-12T12:38:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="SKIP" signature="CreatePro()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="CreatePro" duration-ms="22611" started-at="2022-04-12T12:38:15Z" finished-at="2022-04-12T12:38:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at SeleniumFrameworkWithTestNg.CreateProductTest.CreatePro(CreateProductTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatePro -->
        <test-method status="PASS" signature="LogoutFromApplication()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="LogoutFromApplication" is-config="true" duration-ms="2550" started-at="2022-04-12T12:38:38Z" finished-at="2022-04-12T12:38:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutFromApplication -->
        <test-method status="PASS" signature="LoginToApplication()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="LoginToApplication" is-config="true" duration-ms="4461" started-at="2022-04-12T12:38:41Z" finished-at="2022-04-12T12:38:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="FAIL" signature="CreatePro()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="CreatePro" duration-ms="11406" started-at="2022-04-12T12:38:45Z" finished-at="2022-04-12T12:38:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at SeleniumFrameworkWithTestNg.CreateProductTest.CreatePro(CreateProductTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatePro -->
        <test-method status="PASS" signature="LogoutFromApplication()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="LogoutFromApplication" is-config="true" duration-ms="2155" started-at="2022-04-12T12:38:58Z" finished-at="2022-04-12T12:39:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutFromApplication -->
        <test-method status="PASS" signature="CloseBrowser()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="CloseBrowser" is-config="true" duration-ms="1187" started-at="2022-04-12T12:39:00Z" finished-at="2022-04-12T12:39:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
        <test-method status="PASS" signature="CloseparallelExecution()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="CloseparallelExecution" is-config="true" duration-ms="1" started-at="2022-04-12T12:39:01Z" finished-at="2022-04-12T12:39:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseparallelExecution -->
        <test-method status="PASS" signature="CloseDatabaseConnection()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateProductTest@5f2108b5]" name="CloseDatabaseConnection" is-config="true" duration-ms="0" started-at="2022-04-12T12:39:01Z" finished-at="2022-04-12T12:39:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseDatabaseConnection -->
      </class> <!-- SeleniumFrameworkWithTestNg.CreateProductTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
